[package]
name = "aerobro"
version = "0.0.1"
authors = ["4KB4RPN136 <akbarpn136@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
paho-mqtt = "0.9"
