name: Pengembangan Aerobro

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy_socket:
    name: Deploy SocketIO
    runs-on: server19
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd src_socket
          node -v
          npm -v
          pwd
          npm install

  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
