name: Deploy Aerobro

on:
  push:
    tags:
      - '*'

jobs:
  upload_aerobro:
    name: Upload Aplikasi Aerobro
    runs-on: server15
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Init Directory
        run: |
          mkdir aerobro

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Check and Install Dependencies
        run: |
          cd ui
          node -v
          npm -v
          npm install
          npm install -g @quasar/cli

      - name: Build UI
        run: |
          mkdir aerobro/spa
          cd ui
          cat > .env << ENDOFFILE
          STREAM_ADDRESS=${{ secrets.STREAM_ADDRESS }}
          ACC_THRESHOLD_MIN=0.3
          ACC_THRESHOLD_MAX=0.7
          STRAIN_THRESHOLD_MIN=0.4
          STRAIN_THRESHOLD_MAX=0.6
          DISP_THRESHOLD_MIN=0.4
          DISP_THRESHOLD_MAX=0.6
          REPO_NAME=aerobro
          ENDOFFILE
          quasar build
          cp -r dist/spa/* ../aerobro

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Make Build Main Env.
        run: |
          cat > .env << ENDOFFILE
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          ENDOFFILE

      - name: Build Worker Using Cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Move to Aerobro Directory
        run: |
          mv target/release/aerobro aerobro/
          mv proc/ aerobro/
          ls aerobro/

      - name: Upload UI to Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: aerobro/
          allow_override: true

  deploy_aerobro_ui:
    name: Deploy Aerobro UI
    needs: upload_aerobro
    runs-on: server15
    steps:
      - name: Download Assets
        run: |
          rm -rf *
          wget --no-check-certificate https://github.com/bbta3-bppt/aerobro/releases/latest/download/aerobro.tgz
          tar -xvf aerobro.tgz
          mv aerobro/ aerobros/
          mv aerobros/* .
          rm -r aerobros/
          rm aerobro.tgz

      - name: Make Main Env.
        run: |
          cat > .env << ENDOFFILE
          MQTT_ADDR=${{ secrets.MQTT_ADDR }}
          MQTT_USER=${{ secrets.MQTT_USER }}
          MQTT_PWD=${{ secrets.MQTT_PWD }}
          MSG_TOPIC=${{ secrets.MSG_TOPIC }}
          APP_PORT=3000
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          ENDOFFILE

      - name: Make Proc. Env.
        run: |
          cat > proc/.env << ENDOFFILE
          STREAM_ADDRESS=${{ secrets.WS_ADDRESS }}
          ACC_THRESHOLD_MIN=0.4
          ACC_THRESHOLD_MAX=0.7
          STRAIN_THRESHOLD_MIN=0.4
          STRAIN_THRESHOLD_MAX=0.7
          DISP_THRESHOLD_MIN=3.0
          DISP_THRESHOLD_MAX=3.5
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          ENDOFFILE
