name: Pengembangan Aerobro

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy_socket:
    name: Deploy SocketIO
    runs-on: server19
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Running Socket
        env:
          SOCKET_PORT: 8765
          SOCKET_ROOM_DEFAULT: ${{ secrets.SOCKET_ROOM_DEFAULT }}
        run: |
          cd src_socket
          node -v
          npm -v
          npm install
          pm2 restart aerobrosocket --update-env

  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
